### PR TITLE
Package minifier scripts ft

### LINKED ISSUE #2: include package.json and minifier scripts
I'd be happy to add this if you like on monday... but I would suggest doing a package.json with a peerDependency for bootstrap, and include any build/minifier tools and scripts in the package.json... so you can simply `npm run build` ... also, publishing to npm of course.

In addition, would keep the source under `lib/` or `src/` and the build versions under `dist/` as a structural point...

Nice work by the way.

### PR DESCRIPTION
**Pull request by tracker1**
tweaks to output and configuration...
- npm/node file needs tof be `package.json` not `.txt`
- added dependencies (use `npm install --save-dev FOO` for dependencies
- added `.gitignore` for node project
- removed `npm_modules/` from git
- updated `package.json` for build and watch tasks
- updated `gulpfile.js` for build and watch tasks

Closes #2

### CODE REVIEW

**Comment by cmaddux** [comment]
Wow, thanks very much! I'll have to spend some time going through all of the changes to make sure I understand what's happening. Just so I understand correctly, when this is merged into the master, any change to littlebox.css will automatically run gulpfile.js which will create a minified version of the new littlebox.css in the dist/ folder?

I'll also go ahead and publish littlebox to npm and seems like it should be good to merge with the master. Thanks again!

**Comment by tracker1** [comment]
If you run `npm run watch` it will run gulp watching for changes to the CSS and will indeed update the files in the `dist/` directory.  You can also run `npm run build` which will run gulp with defaults (which is the build task).  I removed the watch as the default gulp task since it's not a good idea for gulp to stay open by default.

**Comment by cmaddux** [comment]
Awesome, works great! I actually built out the icon set in less since there's so much repetition, which should make adding icons easier. I then retooled the gulpfile css function (renamed it less) to use the .less file in lib/ as the source, copy the less to dist/, compile the less to css (copy to dist/), minify the css, etc.

The lib directory now contains only the less file. Should I keep the css file in there as well?

**Comment by tracker1** [comment]
Your generated output should really be under dist/ .. you may want to rename your `lib/` to `src/` since it's not technically usable as-is... but lib/ is generally for files that can be require()'d in as-is, without generators or translation, my $.02 here, everyone does their own thing... I do far more node or js projects than css/less standalones, which is what this really is.

**Comment by cmaddux** [comment]
For sure, makes sense to change lib/ to src/. I'll get that done. Thanks!

**Pull request merged**
